---
options:
  python-version:
    type: int
    default: 3
    description: Openstack base python version(2 or 3)
  triliovault-pkg-source:
    type: string
    default: "deb [trusted=yes] https://apt.fury.io/triliodata-3-4/ /"
    description: Repository address of triliovault packages
  tvault-datamover-virtenv-url:
    type: string
    default:
    description: Downloadable URL of triliovault contego virtual environment
  tvault-datamover-ext-usr:
    type: string
    default: nova
    description: nova service user name
  tvault-datamover-ext-group:
    type: string
    default: nova
    description: nova service group name
  tvault-datamover-virtenv:
    type: string
    default: /home/tvault
    description: Trilio Vault home directory
  tvault-datamover-virtenv-path:
    type: string
    default: /home/tvault/.virtenv
    description: Trilio Vault Datamover virtual env
  tv-datamover-conf:
    type: string
    default: /etc/tvault-contego/tvault-contego.conf
    description: Trilio Vault Datamover config file location
  nova-config:
    type: string
    default: /etc/nova/nova.conf
    description: Nova default configuration file location
  backup-target-type:
    type: string
    default: nfs
    description: |
        Type of backup target.
        Valid types are-
          - nfs
          - s3
  nfs-shares:
    type: string
    default:
    description: NFS Shares mount source path
  nfs-options:
    type: string
    default: nolock,soft,timeo=180,intr,lookupcache=none
    description: NFS Options
  tv-data-dir:
    type: string
    default: /var/triliovault-mounts
    description: TrilioVault data mount point
  tv-data-dir-old:
    type: string
    default: /var/triliovault
    description: Old TrilioVault data dir
  tv-s3-secret-key:
    type: string
    default: sample_s3_secret_key
    description: S3 secret access key
  tv-s3-access-key:
    type: string
    default: sample_s3_access_key
    description: S3 access key
  tv-s3-region-name:
    type: string
    default:
    description: S3 region name
  tv-s3-bucket:
    type: string
    default: sample_s3_bucket_name
    description: S3 bucket name
  tv-s3-endpoint-url:
    type: string
    default:
    description: S3 endpoint URL
  tv-datamover-debug:
    type: boolean
    default: False
    description: debug parameter value in /etc/tvault-contego/tvault-contego.conf
  tv-datamover-verbose:
    type: boolean
    default: True
    description: verbose parameter value in /etc/tvault-contego/tvault-contego.conf
  tv-datamover-max-uploads-pending:
    type: int
    default: 3
    description: max_uploads_pending parameter value in /etc/tvault-contego/tvault-contego.conf
  tv-datamover-max-commit-pending:
    type: int
    default: 3
    description: max_commit_pending parameter value in /etc/tvault-contego/tvault-contego.conf
  tv-datamover-qemu-agent-ping-timeout:
    type: int
    default: 600
    description: qemu_agent_ping_timeout parameter value in /etc/tvault-contego/tvault-contego.conf
